version: "3.8"

services:
  face-recognition-dev:
    build: ./
    container_name: face-recognition-dev
    image: face-recognition-arm/v7
    volumes:
      - ./:/app
    ports:
      - "80:80"
    # devices:
    #   # カメラデバイスをコンテナに接続
    #   - "/dev/video0:/dev/video0"
    stdin_open: true
    tty: true
